import { WcAttribute } from "../attribute/wc-attribute.model";
import { WcCategory } from "../category/wc-category.model";
import { WcDefaultAttribute } from "../default-attribute/wc-default-attribute.model";
import { WcDimensions } from "../dimensions/wc-dimensions.model";
import { WcDownload } from "../download/wc-download.model";
import { WcImage } from "../image/wc-image.model";
import { WcMetaData } from "../meta-data/wc-meta-data.model";
import { WcTag } from "../tag/wc-tag.model";

export interface WooCommerceProduct {
    id: number;
    name: string;
    slug: string;
    permalink: string;
    date_created: Date;
    date_created_gmt: Date;
    date_modified: Date;
    type: string;
    status: string;
    featured: boolean;
    catalog_visibility: string;
    description: string;
    short_description: string;
    sku: string;
    price: string;
    sale_price: string;
    date_on_sale_from: Date;
    date_on_sale_from_gmt: Date;
    date_on_sale_to: Date;
    date_on_sale_to_gmt: Date;
    price_html: string;
    on_sale: boolean;
    purchasable: boolean;
    total_sales: number;
    virtual: boolean;
    downloadable: boolean;
    downloads: WcDownload[];
    download_limit: number;
    download_expiry: number;
    external_url: string;
    button_text: string;
    tax_status: string;
    tax_class: string;
    manage_stock: boolean;
    stock_quantity: number;
    stock_status: string;
    backorders: string;
    backorders_allowed: boolean;
    backordered: boolean;
    sold_individually: boolean;
    weight: string;
    dimensions: WcDimensions;
    shipping_required: boolean;
    shipping_taxable: boolean;
    shipping_class: string;
    shipping_class_id: number;
    reviews_allowed: boolean;
    average_rating: string;
    rating_count: number;
    related_ids: any[];
    upsell_ids: any[];
    cross_sell_ids: any[];
    parent_id: number;
    purchase_note: string;
    categories: WcCategory[];
    tags: WcTag[];
    images: WcImage[];
    attributes: WcAttribute[];
    default_attributes: WcDefaultAttribute[];
    variations: any[];
    grouped_products: any[];
    menu_order: number;
    meta_data: WcMetaData[];
}