import { Attribute } from "../attribute/attribute.model";
import { Category } from "../category/category.model";
import { DefaultAttribute } from "../default-attribute/default-attribute.model";
import { Dimensions } from "../dimensions/dimensions.model";
import { Download } from "../download/download.model";
import { Image } from "../image/image.model";
import { MetaData } from "../meta-data/meta-data.model";
import { Tag } from "../tag/tag.model";

export interface WooCommerceProduct {
    id: number;
    name: string;
    slug: string;
    permalink: string;
    date_created: Date;
    date_created_gmt: Date;
    date_modified: Date;
    type: string;
    status: string;
    featured: boolean;
    catalog_visibility: string;
    description: string;
    short_description: string;
    sku: string;
    price: string;
    sale_price: string;
    date_on_sale_from: Date;
    date_on_sale_from_gmt: Date;
    date_on_sale_to: Date;
    date_on_sale_to_gmt: Date;
    price_html: string;
    on_sale: boolean;
    purchasable: boolean;
    total_sales: number;
    virtual: boolean;
    downloadable: boolean;
    downloads: Download[];
    download_limit: number;
    download_expiry: number;
    external_url: string;
    button_text: string;
    tax_status: string;
    tax_class: string;
    manage_stock: boolean;
    stock_quantity: number;
    stock_status: string;
    backorders: string;
    backorders_allowed: boolean;
    backordered: boolean;
    sold_individually: boolean;
    weight: string;
    dimensions: Dimensions;
    shipping_required: boolean;
    shipping_taxable: boolean;
    shipping_class: string;
    shipping_class_id: number;
    reviews_allowed: boolean;
    average_rating: string;
    rating_count: number;
    related_ids: any[];
    upsell_ids: any[];
    cross_sell_ids: any[];
    parent_id: number;
    purchase_note: string;
    categories: Category[];
    tags: Tag[];
    images: Image[];
    attributes: Attribute[];
    default_attributes: DefaultAttribute[];
    variations: any[];
    grouped_products: any[];
    menu_order: number;
    meta_data: MetaData[];
}